export const UFS = [
  "AC","AL","AP","AM","BA","CE","DF","ES","GO","MA",
  "MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN",
  "RS","RO","RR","SC","SP","SE","TO",
]

export const MUNICIPIOS: Record<string, string[]> = {
  AC: ["Rio Branco","Cruzeiro do Sul","Sena Madureira","Senador Guiomard","Tarauacá"],
  AL: ["Maceió","Arapiraca","Rio Largo","Palmeira dos Índios","Penedo","Marechal Deodoro"],
  AP: ["Macapá","Santana","Laranjal do Jari","Oiapoque","Mazagão"],
  AM: ["Manaus","Parintins","Itacoatiara","Manacapuru","Coari","Tefé"],
  BA: ["Salvador","Feira de Santana","Vitória da Conquista","Camaçari","Juazeiro","Ilhéus","Lauro de Freitas","Itabuna"],
  CE: ["Fortaleza","Caucaia","Juazeiro do Norte","Maracanaú","Sobral","Crato","Itapipoca","Maranguape"],
  DF: ["Brasília"],
  ES: ["Vitória","Serra","Cariacica","Vila Velha","Cachoeiro de Itapemirim","Linhares","São Mateus"],
  GO: ["Goiânia","Aparecida de Goiânia","Anápolis","Rio Verde","Luziânia","Águas Lindas de Goiás"],
  MA: ["São Luís","Imperatriz","São José de Ribamar","Timon","Caxias","Codó","Açailândia"],
  MT: ["Cuiabá","Várzea Grande","Rondonópolis","Sinop","Tangará da Serra","Cáceres"],
  MS: ["Campo Grande","Dourados","Três Lagoas","Corumbá","Ponta Porã","Naviraí"],
  MG: ["Belo Horizonte","Uberlândia","Contagem","Juiz de Fora","Betim","Montes Claros","Uberaba","Ipatinga","Sete Lagoas","Divinópolis","Governador Valadares"],
  PA: ["Belém","Ananindeua","Santarém","Marabá","Parauapebas","Castanhal","Abaetetuba"],
  PB: ["João Pessoa","Campina Grande","Santa Rita","Patos","Bayeux","Sousa"],
  PR: ["Curitiba","Londrina","Maringá","Ponta Grossa","Cascavel","São José dos Pinhais","Foz do Iguaçu","Colombo"],
  PE: ["Recife","Caruaru","Olinda","Petrolina","Paulista","Jaboatão dos Guararapes","Vitória de Santo Antão"],
  PI: ["Teresina","Parnaíba","Picos","Piripiri","Floriano","Campo Maior"],
  RJ: ["Rio de Janeiro","São Gonçalo","Duque de Caxias","Nova Iguaçu","Niterói","Belford Roxo","Campos dos Goytacazes","Petrópolis","Volta Redonda","Magé"],
  RN: ["Natal","Mossoró","Parnamirim","São Gonçalo do Amarante","Caicó","Açu"],
  RS: ["Porto Alegre","Caxias do Sul","Pelotas","Canoas","Santa Maria","Gravataí","Viamão","Novo Hamburgo","São Leopoldo"],
  RO: ["Porto Velho","Ji-Paraná","Ariquemes","Vilhena","Cacoal","Rolim de Moura"],
  RR: ["Boa Vista","Rorainópolis","Caracaraí","Mucajaí"],
  SC: ["Florianópolis","Joinville","Blumenau","São José","Criciúma","Chapecó","Itajaí","Jaraguá do Sul"],
  SP: ["São Paulo","Guarulhos","Campinas","São Bernardo do Campo","Santo André","Osasco","São José dos Campos","Ribeirão Preto","Sorocaba","Santos","Jundiaí","Piracicaba","Bauru","Mauá","São Caetano do Sul","Diadema","Carapicuíba","Mogi das Cruzes","Suzano"],
  SE: ["Aracaju","Nossa Senhora do Socorro","Lagarto","Itabaiana","São Cristóvão","Estância"],
  TO: ["Palmas","Araguaína","Gurupi","Porto Nacional","Paraíso do Tocantins","Guaraí"],
}
